#!/usr/bin/env python

from sys import argv, path, stderr
from os.path import dirname, abspath

app_dir = dirname(abspath(argv[0]))
path.append(app_dir + '/python')

import rox
from rox import g

message=rox._("ROX-Lib2 contains code that is useful to newer ROX applications. \
You should place this directory somewhere where other programs can \
find it, such as ~/lib or /usr/local/lib.\n\n\
ROX-Lib version: %s\n\
PyGTK version: %s\n\
GTK version: %s\n\n\
PyGTK location:\n%s") % (rox.roxlib_version, g.pygtk_version, g.gtk_version, dirname(g.__file__))

if rox.g.gdk.display_get_default() is not None:
	box = g.MessageDialog(None, g.MESSAGE_QUESTION, 0, g.BUTTONS_OK, message)
	box.add_button(g.STOCK_HELP, g.RESPONSE_HELP)
	box.set_title('ROX-Lib')
	box.set_position(g.WIN_POS_CENTER)
	box.set_default_response(g.RESPONSE_OK)

	if box.run() == int(g.RESPONSE_HELP):
		from rox import filer
		import os.path
		filer.open_dir(os.path.join(app_dir, "Help"))
		
else:
	stderr.write(message+'\n')

