#!/usr/bin/env python3

from sys import argv, path, stderr
from os.path import dirname, abspath

app_dir = dirname(abspath(argv[0]))
path.append(app_dir + '/python')

import rox

import gi
from gi.repository import Gtk, Gdk

message=rox._("ROX-Lib3 contains code that is useful to newer ROX applications. \
You should place this directory somewhere where other programs can \
find it, such as ~/lib or /usr/local/lib.\n\n\
ROX-Lib version: %s\n\
PyGObject version: %s\n\
GTK version: %s\n\n\
") % (
	'%d.%d.%d' % rox.roxlib_version,
        gi.__version__,
	'%d.%d.%d' % (
		Gtk.get_major_version(),
		Gtk.get_minor_version(),
		Gtk.get_micro_version()
	)
)

if Gdk.Display.get_default() is not None:
	box = Gtk.MessageDialog(None, Gtk.MessageType.QUESTION, 0, Gtk.ButtonsType.OK, message)
	box.add_button(Gtk.STOCK_HELP, Gtk.ResponseType.HELP)
	box.set_title('ROX-Lib')
	box.set_position(Gtk.WindowPosition.CENTER)
	box.set_default_response(Gtk.ResponseType.OK)

	if box.run() == int(Gtk.ResponseType.HELP):
		from rox import filer
		import os.path
		filer.open_dir(os.path.join(app_dir, "Help"))
		
else:
	stderr.write(message+'\n')

