#!/bin/sh

echo Extracting messages from source files...
echo

(cd ../python/rox; pygettext *.py ../../AppRun)

echo
echo Updating all .po files...
echo

for FILE in *.po; do
	echo -n "Updating '$FILE' translation"
	mv $FILE $FILE.old
	msgmerge $FILE.old ../python/rox/messages.pot > $FILE
done
